### PR TITLE
Use GHA's token

### LINKED ISSUE #336: Resupport GH Auth
I looked into this some in #310, and I'm pretty certain our workflows aren't set up correctly.

First off, we never pass the secret into the environment. #310 fixes that.
Next off, we're using username:token. Why do we need a username? If we pass in a token, the API knows who's associated with that. Moreover, the code uses "password" for token, leading me to think that perhaps it was from when the API supported password auth?
Then, we should also specify the version of the REST API we want, which will prevent breaking changes.
Oh, and we're passing the token in using HTTP Basic Auth which a) is very insecure and b) is only support for GitHub Apps' tokens, not user tokens.

So... I think that's why we hit rate limits a lot.
I think #310 covers it all, ~~but it's failing CI on a genuine error, last I checked (I should try rebasing once main is green again)~~ EDIT: rebased, green, seems to work well.

### PR DESCRIPTION
**Pull request by lishaduck**
GHA provides a token itself, we don't need to generate one. This is more-fine grained, easier to change if needed, and more secure.

I think the existing `contents: read` is sufficient, but it might not be. We'll see.

Based on https://github.com/jfmengels/node-elm-review/pull/309#issuecomment-2467063929.

Closes #336.

### CODE REVIEW

**Comment by lishaduck** [comment]
Oh, github-auth needs a username. I'll think on this.

**Comment by lishaduck** [comment]
Ok, so the GITHUB_TOKEN is for a builtin github app, not your own account, so that i.e., contributing to a project with extensive doesn't use up your personal rate. Thus, there's not a username associated with it. However, I think we don't need a username to make authenticated requests, do we? Could we make it optional?

**Comment by lishaduck** [comment]
Hmm, looks like it's not picking up AUTH_GITHUB.

**Comment by lishaduck** [comment]
Hit #313.

**Comment by lishaduck** [comment]
I'll try to rebase this when I get a moment, I still think this should fix rate limiting (because secrets isn't injected into ENV), and still obsolete needing @jfmengels' token.

File: lib/remote-template.js [hunk 1]
```diff
@@ -197,21 +197,31 @@ ${error.message}`
...
+/**
+ * @param {boolean} hasPat
+ * @param {string} resetTime
+ * @returns {ErrorMessageInfo}
+ */
+function rateLimitErrorMessage(hasPat, resetTime) {
+  return {
+    title: 'GITHUB RATE LIMIT EXCEEDED',
+    message: `It looks like you exceeded the GitHub rate limit by using "--template" too many
+times, this will likely last until ${resetTime}.
```
Comment (jfmengels) [inline lib/remote-template.js:209]: This is so nice to have!

**Comment by jfmengels** [comment]
This looks to work promisingly.

**Comment by lishaduck** [comment]
It passes CI now!
